# only used for inference!
GPUS: (0, )
BACKBONE_MODEL: hrnet
# MODEL: multiview_pose_hrnet
DATA_DIR: ""
OUTPUT_DIR: "output"
LOG_DIR: "log"
WORKERS: 8
PRINT_FREQ: 100

DATASET:
  # COLOR_RGB: true
  TRAIN_DATASET: coco
  TEST_DATASET: coco
  DATA_FORMAT: jpg
  ROOT: "data/"
  COCO_ROT_FACTOR: 45
  COCO_SCALE_FACTOR: 0.35
  COCO_FLIP: true
  TEST_SUBSET: "val2017"
  TRAIN_SUBSET: "train2017"
NETWORK:
  NUM_JOINTS: 17
  PRETRAINED: "checkpoints/hrnet_w32-36af842e_coco.pth"
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
    - 192 # width
    - 256 # height
  HEATMAP_SIZE:
    - 48
    - 64
  SIGMA: 2
MODEL_EXTRA:
  PRETRAINED_LAYERS:
    - "conv1"
    - "bn1"
    - "conv2"
    - "bn2"
    - "layer1"
    - "transition1"
    - "stage2"
    - "transition2"
    - "stage3"
    - "transition3"
    - "stage4"
  FINAL_CONV_KERNEL: 1
  STAGE2:
    NUM_MODULES: 1
    NUM_BRANCHES: 2
    BLOCK: BASIC
    NUM_BLOCKS:
      - 4
      - 4
    NUM_CHANNELS:
      - 32
      - 64
    FUSE_METHOD: SUM
  STAGE3:
    NUM_MODULES: 4
    NUM_BRANCHES: 3
    BLOCK: BASIC
    NUM_BLOCKS:
      - 4
      - 4
      - 4
    NUM_CHANNELS:
      - 32
      - 64
      - 128
    FUSE_METHOD: SUM
  STAGE4:
    NUM_MODULES: 3
    NUM_BRANCHES: 4
    BLOCK: BASIC
    NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
    NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
    FUSE_METHOD: SUM
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 32
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 210
  OPTIMIZER: adam
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
    - 170
    - 200
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 32
  # COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  MODEL_FILE: "checkpoints/pose_hrnet_w32_256x192_coco.pth"
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
  FLIP_TEST: false
  POST_PROCESS: true
  SHIFT_HEATMAP: true
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
